# inventory/hosts.yml
# Define your hosts and groups here.
# See: https://docs.ansible.com/ansible/latest/inventory_guide/intro_inventory.html

all:
  children:
    fs01_group: #This makes it so changes only apply to my server when I make them <3 
      hosts:
        fs01:
          ansible_host: 10.0.0.227
          ansible_user: sdavis
