# inventory/hosts.yml
# Define your hosts and groups here.
# See: https://docs.ansible.com/ansible/latest/inventory_guide/intro_inventory.html

all:
  hosts:
    fs01:
      ansible_host: 10.30.10.13
      ansible_user: sdavis
